export const actionTypes = {
	GET_AUTHORS: 'GET_AUTHORS',
	SET_AUTHORS: 'SET_AUTHORS',
	ADD_AUTHOR: 'ADD_AUTHOR',
	DELETE_AUTHOR: 'DELETE_AUTHOR',
	RESET_FORM: 'RESET_FORM',
	RESET_AUTHOR_FORM: 'RESET_AUTHOR_FORM',
};
