export const actionTypes = {
	GET_COURSE: 'GET_COURSE',
	SET_COURSES: 'SET_COURSES',
	ADD_COURSE: 'ADD_COURSE',
	DELETE_COURSE: 'DELETE_COURSE',
	UPDATE_COURSE: 'UPDATE_COURSE',
	SET_NEW_COURSE: 'SET_NEW_COURSE',
};
